export const appRoutes = {
  home: "/",
  dashboard: "/dashboard",
  dashboardSales: "/dashboard/sales",
  dashboardPurchases: "/dashboard/purchases",
  dashboardProducts: "/dashboard/products",
  dashboardPartners: "/dashboard/partners",
  dashboardAccounts: "/dashboard/accounts",
  dashboardTransfers: "/dashboard/transfers",
  dashboardReports: "/dashboard/reports",
  profile: "/dashboard/profile",
  myListings: "/dashboard/products",
  newListing: "/dashboard/products",
  listingDetail: (id: string | number) => `/dashboard/products?product=${id}`,
  listingEdit: (id: string | number) => `/dashboard/products?product=${id}`,
  dashboardNotifications: "/dashboard/notifications",
  dashboardNotificationDetail: (
    id: string | number,
    source?: "user" | "owner",
  ) => `/dashboard/notifications/${id}${source ? `?source=${source}` : ""}`,
  dashboardFavorites: "/dashboard/products",
  dashboardSettings: "/dashboard/settings",
  dashboardOnwerArticle: "/dashboard/reports",
  dashboardOnwerArticleNew: `/dashboard/reports`,
  dashboardOnwerArticleEdit: (id: string) => `/dashboard/reports?article=${id}`,
  dashboardVerifyEmail: "/dashboard/verify-email",
  dashboardBecomeOwner: "/dashboard/settings",
  ownerProfile: (id: string | number) => `/owners/${id}`,
  login: "/login",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  properties: "/properties",
  agencies: "/agencies",
  register: "/register",
  devHealth: "/dev/health",
  adminLogin: "/admin/login",
  adminDashboard: "/admin/dashboard",
  adminJournals: "/admin/journals",
  adminSettingsUsers: "/admin/settings/users",
  adminSales: "/admin/sales",
  adminPurchases: "/admin/purchases",
  adminProducts: "/admin/products",
  adminPartners: "/admin/partners",
  adminAccounts: "/admin/accounts",
  adminAccountDetails: (id: string | number) => `/admin/accounts/${id}`,
  adminTransfers: "/admin/transfers",
  adminReports: "/admin/reports",
  adminUsers: "/admin/settings/users",
  adminUsersTab: (tab: "all" | "reports") =>
    tab === "all"
      ? "/admin/settings/users"
      : `/admin/settings/users?tab=${tab}`,
  adminUserDetails: (id: string | number) =>
    `/admin/settings/users/${id}/details`,
  adminUserReports: (id: string | number) =>
    `/admin/settings/users/${id}/reports`,
  adminUsersReports: "/admin/settings/users?tab=reports",
  adminOwners: "/admin/partners",
  adminAgencies: "/admin/partners",
  adminAgenciesTab: (tab: "all" | "approvals") =>
    tab === "all" ? "/admin/partners" : `/admin/partners?tab=${tab}`,
  adminAgencyDetails: (id: string | number) => `/admin/partners?partner=${id}`,
  adminAgencyReview: (id: string | number) => `/admin/partners?review=${id}`,
  adminAgencySubscription: (id: string | number) =>
    `/admin/partners?subscription=${id}`,
  adminAgenciesApprovals: "/admin/partners?tab=approvals",
  adminAgenciesSubscriptions: "/admin/partners?tab=subscriptions",
  adminProperties: "/admin/products",
  adminPropertiesFeatured: "/admin/products",
  adminPropertiesApprovals: "/admin/products",
  adminPropertiesAmenities: "/admin/products",
  adminPropertiesCategories: "/admin/products",
  adminCategoryDetails: (id: string | number) =>
    `/admin/products?category=${id}`,
  adminListings: "/admin/products",
  adminListingsTab: (tab: "all" | "categories" | "amenities" | "featured") =>
    tab === "all" ? "/admin/products" : `/admin/products?tab=${tab}`,
  adminListingDetail: (id: string | number) => `/admin/products?product=${id}`,
  adminListingDetails: (id: string | number) => `/admin/products?product=${id}`,
  adminListingReview: (id: string | number) => `/admin/products?review=${id}`,
  adminRentals: "/admin/sales",
  adminRentalsApprovals: "/admin/sales?tab=approvals",
  adminLeads: "/admin/partners",
  adminReviews: "/admin/reports",
  adminContentNews: "/admin/reports",
  adminContentNewsNew: "/admin/reports",
  adminContentNewsDetail: (id: string | number) => `/admin/reports?item=${id}`,
  adminContentNewsEdit: (id: string | number) => `/admin/reports?edit=${id}`,
  adminContentCategories: "/admin/reports",
  adminContentMedia: "/admin/settings",
  publicNews: "/login",
  publicArticle: (slug: string) => `/login?article=${slug}`,
  adminAdvertisements: "/admin/settings",
  adminPromotionPlans: "/admin/settings",
  adminPaymentsTransactions: "/admin/payments/transactions",
  adminPaymentsInvoices: "/admin/payments/invoices",
  adminSupport: "/admin/support",
  adminAnalytics: "/admin/analytics",
  adminSettings: "/admin/settings",
  adminSettingsSection: (section: string) => `/admin/settings/${section}`,
  adminSettingsGeneral: "/admin/settings/general",
  adminSettingsLocations: "/admin/settings/locations",
  adminSettingsNotifications: "/admin/settings/notifications",
  adminSettingsSecurity: "/admin/settings/security",
} as const;
